### ISSUE TITLE
เปิดใช้งาน Travis

### ISSUE THREAD

**Issue by sitdh** [we-inc/mms-snow-white-and-the-seven-pandas#1]
@we-inc/snow-white-and-the-seven-pandas @futurizing ต้องการใช้งาน Travis CI ด้วยใช้ไหมครับ

**Comment by futurizing** [comment]
ถ้าเป็นไปได้ก็อยากใช้งานครับ :)

**Comment by sitdh** [comment]
@futurizing รับทราบครับ เดี๋ยวพี่ grant ให้ (เตรียมเนื้อหาไว้ท้ายๆ พอดี)

**Comment by sitdh** [comment]
เรียบร้อยครับ ปรับให้แล้ว

**Comment by futurizing** [comment]
ขอบคุณครับ 👍
