### ISSUE TITLE
The image's URL is incorrect when requesting via proxy

### ISSUE THREAD

**Issue by futurizing** [we-inc/mms-snow-white-and-the-seven-pandas#159]
**Expected URL** 

`http://localhost:8000/media/cover_photos/2017/11/15/ABC.jpg`

**Received URL**

 `http://localhost:4200/media/cover_photos/2017/11/15/ABC.jpg`

Note that this URL is received from the webserver through the proxy.

**Comment by JThanat** [comment]
Didn't you fix that?

**Comment by JThanat** [comment]
Do you prefer using url like `/media/scene_photo/2017/11/20/ABC.png` instead?

**Comment by futurizing** [comment]
@JThanat For now it's `url.replace('8000', '4200')`, which is super hacky.

One of the solutions is, in addition to `/api` proxying, I will proxy `/media/` from `4200` to `8000`, too. Is that OK?
