### ISSUE TITLE
Acceptance Criteria

### ISSUE THREAD

**Issue by JThanat** [we-inc/mms-snow-white-and-the-seven-pandas#24]
### Expected Outcome
* Completed Acceptance Criteria and Table

### Current State
- [x] Complete written description information
- [x] Complete bullets list of topics
- [x]  Check grammar
- [x] Add more criteria in table 6.2.1 (View TODO)
- [x] Complete table 6.2.2 (View TODO)

**Comment by pirsquareff** [comment]
Done in PR #37.
